export const Questions = [
    'Little interest or pleasure in doing things',
    'Feeling down, depressed, or hopeless',
    'Thoughts that you would be better off dead, or thoughts of hurting yourself in some way?',
    'Feeling nervous, anxious, or on edge',
    'Not being able to stop or control worrying',
    'I find it difficult to mix comfortably with the people I work with.',
    'I am at ease meeting people at parties, etc.',
    'I have difficulty talking with other people.',
    'I worry about expressing myself in case I appear awkward.',
    'I find myself worrying that I won\'t know what to say in social situations.',
    'How often do you have trouble wrapping up the final details of a project, once the challenging parts have been done?',
    'How often do you have difficulty getting things in order when you have to do a task that requires organization?',
    'How often do you have problems remembering appointments or obligations?',
    'When you have a task that requires a lot of thought, how often do you avoid or delay getting started?',
    'How often do you fidget or squirm with your hands or feet when you have to sit down for a long time?',
    'How often do you feel overly active and compelled to do things, like you were driven by a motor?',
    'Every time someone treats me like my assigned sex I feel hurt',
    'It feels good to live as my affirmed gender',
    'A life in my affirmed gender is more attractive for me than a life in my assigned sex',
    'I wish I had been born as my affirmed gender',
    'I feel unhappy when someone misgenders me',
    'Memories of trauma come to mind at unwanted moments',
    'At random times, I feel a burst of anger and/or guilt about past trauma',
    'I feel a physical effect when remembering a past trauma, effects can range from racing pulse, excessive sweating, chills or shaking?'
  ];

  export const QuestionCategory = [
    'Depression', 'Depression', 'Depression', 'Generalized Anxiety', 'Generalized Anxiety', 
    'Social Anxiety', 'Social Anxiety', 'Social Anxiety', 'Social Anxiety', 'Social Anxiety', 
    'ADHD', 'ADHD', 'ADHD', 'ADHD', 'ADHD', 'ADHD', 'Gender Dysphoria', 'Gender Dysphoria', 
    'Gender Dysphoria', 'Gender Dysphoria', 'Gender Dysphoria', 'PTSD', 'PTSD', 'PTSD'
  ];

  export const ResponseOptions = [
    ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'],
    ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'],
    ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'],
    ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'],
    ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'],
    ['Not at all', 'Slightly', 'Moderately', 'Very', 'Extremely'],
    ['Not at all', 'Slightly', 'Moderately', 'Very', 'Extremely'],
    ['Not at all', 'Slightly', 'Moderately', 'Very', 'Extremely'],
    ['Not at all', 'Slightly', 'Moderately', 'Very', 'Extremely'],
    ['Not at all', 'Slightly', 'Moderately', 'Very', 'Extremely'],
    ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
    ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
    ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
    ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
    ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
    ['Never', 'Rarely', 'Sometimes', 'Often', 'Very Often'],
    ['Disagree completely', 'Disagree', 'Neither agree nor disagree', 'Agree', 'Agree completely'],
    ['Disagree completely', 'Disagree', 'Neither agree nor disagree', 'Agree', 'Agree completely'],
    ['Disagree completely', 'Disagree', 'Neither agree nor disagree', 'Agree', 'Agree completely'],
    ['Disagree completely', 'Disagree', 'Neither agree nor disagree', 'Agree', 'Agree completely'],
    ['Disagree completely', 'Disagree', 'Neither agree nor disagree', 'Agree', 'Agree completely'],
    ['Disagree completely', 'Disagree', 'Neither agree nor disagree', 'Agree', 'Agree completely'],
    ['Disagree completely', 'Disagree', 'Neither agree nor disagree', 'Agree', 'Agree completely'],
    ['Disagree completely', 'Disagree', 'Neither agree nor disagree', 'Agree', 'Agree completely']
  ];

  export const ScoringKey = [
    [0, 11.11, 22.22, 33.33],
    [0, 11.11, 22.22, 33.33],
    [0, 11.11, 22.22, 33.33],
    [0, 16.67, 33.33, 50],
    [0, 16.67, 33.33, 50],
    [0, 5, 10, 15, 20],
    [20, 15, 10, 5, 0],
    [0, 5, 10, 15, 20],
    [0, 5, 10, 15, 20],
    [0, 5, 10, 15, 20],
    [0, 0, 16.67, 16.67, 16.67],
    [0, 0, 16.67, 16.67, 16.67],
    [0, 0, 16.67, 16.67, 16.67],
    [0, 0, 0, 16.67, 16.67],
    [0, 0, 0, 16.67, 16.67],
    [0, 0, 0, 16.67, 16.67],
    [0, 0, 0, 10, 20],
    [0, 0, 0, 10, 20],
    [0, 0, 0, 10, 20],
    [0, 0, 0, 10, 20],
    [0, 0, 0, 10, 20],
    [0, 0, 0, 16.67, 33.33],
    [0, 0, 0, 16.67, 33.33],
    [0, 0, 0, 16.67, 33.33]
  ];